package mml.mmlclib.semantic

import mml.mmlclib.ast.*
import mml.mmlclib.compiler.CompilerState

/** Generates memory management functions (`__free_T` and `__clone_T`) for user-defined structs that
  * contain heap-allocated fields.
  *
  * This phase runs after ConstructorGenerator and before RefResolver. For each user struct with
  * heap fields, it generates:
  *   - `__free_StructName(s: StructName): Unit` - frees all heap fields
  *   - `__clone_StructName(s: StructName): StructName` - deep copies all heap fields
  *
  * Native types (String, Buffer, etc.) have their memory functions defined in the C runtime.
  */
object MemoryFunctionGenerator:
  private val syntheticSource = SourceOrigin.Synth

  private def unitTypeRef(source: SourceOrigin): TypeRef =
    TypeRef(source, "Unit", Some("stdlib::typedef::Unit"), Nil)

  private def rawPtrTypeRef(source: SourceOrigin): TypeRef =
    TypeRef(source, "RawPtr", Some("stdlib::typedef::RawPtr"), Nil)

  /** Generate a stable ID for generated memory functions */
  private def genId(moduleName: String, fnName: String): Option[String] =
    Some(s"$moduleName::bnd::$fnName")

  /** Resolve the stable ID for a memory function (free/clone) reference.
    *
    * User-defined structs have their free/clone generated by this generator in the current module.
    * Native types look up stdlib first, then fall back to user-module declarations (e.g. free=).
    */
  private def resolveMemFnId(
    fieldTypeName: String,
    fnName:        String,
    moduleName:    String,
    resolvables:   ResolvablesIndex
  ): Option[String] =
    if TypeUtils.isStructWithHeapFields(fieldTypeName, resolvables) then genId(moduleName, fnName)
    else
      val stdlibId = s"stdlib::bnd::$fnName"
      if resolvables.lookup(stdlibId).isDefined then Some(stdlibId)
      else
        resolvables.resolvables.collectFirst:
          case (id, bnd: Bnd) if bnd.name == fnName => id

  private def isHeapField(field: Field, resolvables: ResolvablesIndex): Boolean =
    isNativeHeapField(field.typeSpec, resolvables)

  private def isNativeHeapField(fieldType: Type, resolvables: ResolvablesIndex): Boolean =
    TypeUtils.getTypeName(fieldType).exists(TypeUtils.isHeapType(_, resolvables))

  private def isFunctionField(field: Field): Boolean =
    TypeUtils.isFunctionType(field.typeSpec)

  /** A field is an ownership sink when it holds heap memory or a function value: the constructor
    * consumes it and the destructor frees it.
    */
  private def isOwnedField(field: Field, resolvables: ResolvablesIndex): Boolean =
    isHeapField(field, resolvables) || isFunctionField(field)

  private def structHasOwnedFields(struct: TypeStruct, resolvables: ResolvablesIndex): Boolean =
    struct.fields.exists(isOwnedField(_, resolvables))

  /** Build the free call for one owned struct field: `__free_T s.field` for a heap field, or
    * `__free_closure s.field` for a function-value field. The universal closure destructor extracts
    * the env pointer from the fat pointer, so a null-env value frees as a safe no-op.
    */
  private def mkFieldFreeCall(
    field:       Field,
    paramName:   String,
    structTR:    TypeRef,
    moduleName:  String,
    unitTR:      TypeRef,
    resolvables: ResolvablesIndex
  ): Option[App] =
    val paramRef = Ref(SourceOrigin.Synth, paramName, typeSpec = Some(structTR))
    val fieldRef = Ref(
      SourceOrigin.Synth,
      field.name,
      qualifier = Some(paramRef),
      typeSpec  = Some(field.typeSpec)
    )
    val argExpr = Expr(syntheticSource, List(fieldRef), typeSpec = Some(field.typeSpec))
    if isFunctionField(field) then
      val freeFnRef = Ref(
        SourceOrigin.Synth,
        "__free_closure",
        resolvedId = Some(s"$moduleName::bnd::__free_closure"),
        typeSpec = Some(
          TypeFn(
            syntheticSource,
            cats.data.NonEmptyList.one(rawPtrTypeRef(syntheticSource)),
            unitTR
          )
        )
      )
      Some(App(syntheticSource, freeFnRef, argExpr, typeSpec = Some(unitTR)))
    else
      TypeUtils.getTypeName(field.typeSpec).flatMap { typeName =>
        TypeUtils.freeFnFor(typeName, resolvables).map { freeFnName =>
          val freeFnRef = Ref(
            SourceOrigin.Synth,
            freeFnName,
            resolvedId = resolveMemFnId(typeName, freeFnName, moduleName, resolvables),
            typeSpec =
              Some(TypeFn(syntheticSource, cats.data.NonEmptyList.one(field.typeSpec), unitTR))
          )
          App(syntheticSource, freeFnRef, argExpr, typeSpec = Some(unitTR))
        }
      }

  /** Chain free calls into a destructor body: `let _ = free1; ... ; freeN`, or unit when empty. */
  private def mkFreeBody(freeCalls: List[Term], unitTR: TypeRef): Expr =
    if freeCalls.isEmpty then
      Expr(
        syntheticSource,
        List(LiteralUnit(syntheticSource, typeSpec = Some(unitTR), typeAsc = None))
      )
    else
      val lastCall  = freeCalls.last
      val initCalls = freeCalls.init

      val innerBody = Expr(syntheticSource, List(lastCall), typeSpec = Some(unitTR))
      initCalls.foldRight(innerBody) { (call, acc) =>
        val discardParam =
          FnParam(
            SourceOrigin.Synth,
            Name.synth("_"),
            typeSpec = Some(unitTR),
            typeAsc  = Some(unitTR)
          )
        val wrapper =
          Lambda(syntheticSource, List(discardParam), acc, Nil, typeSpec = Some(unitTR))
        val callExpr = Expr(syntheticSource, List(call), typeSpec = Some(unitTR))
        Expr(
          syntheticSource,
          List(App(syntheticSource, wrapper, callExpr, typeSpec = Some(unitTR))),
          typeSpec = Some(unitTR)
        )
      }

  /** Build a `__free_StructName` function for a user struct.
    *
    * Generated pattern: {{{ fn __free_User(~u: User): Unit = let _ = __free_String u.name;
    * __free_String u.role }}}
    *
    * Function-value fields are freed through `__free_closure`, which only exists after
    * `ClosureMemoryFnGenerator` runs. They are included via `includeFunctionFields` when this
    * destructor is regenerated by `wireStructClosureFrees` after type checking.
    */
  private def mkFreeFunction(
    struct:                TypeStruct,
    moduleName:            String,
    resolvables:           ResolvablesIndex,
    includeFunctionFields: Boolean
  ): Bnd =
    val structName = struct.name
    val fnName     = s"__free_$structName"
    val paramName  = "s"

    // Type refs
    val structTypeRef =
      TypeRef(syntheticSource, structName, struct.id, Nil)
    val unitTR = unitTypeRef(syntheticSource)

    // Parameter - consuming since it takes ownership
    val param = FnParam(
      SourceOrigin.Synth,
      Name.synth(paramName),
      typeAsc   = Some(structTypeRef),
      consuming = true
    )

    // Fields to free: heap fields always; function-value fields only once __free_closure exists.
    val fieldsToFree = struct.fields.filter { field =>
      isHeapField(field, resolvables) || (includeFunctionFields && isFunctionField(field))
    }

    // Build free calls for each owned field
    val freeCalls: List[Term] = fieldsToFree.toList.flatMap { field =>
      mkFieldFreeCall(field, paramName, structTypeRef, moduleName, unitTR, resolvables)
    }

    val body = mkFreeBody(freeCalls, unitTR)

    // Build the function type: StructName -> Unit
    val fnType = TypeFn(syntheticSource, cats.data.NonEmptyList.one(structTypeRef), unitTR)

    // Build the lambda
    val lambda = Lambda(
      syntheticSource,
      List(param),
      body,
      Nil,
      typeSpec = Some(fnType),
      typeAsc  = Some(unitTR)
    )

    // Build the binding
    val meta = BindingMeta(
      origin        = BindingOrigin.Destructor,
      arity         = CallableArity.Unary,
      precedence    = Precedence.Function,
      associativity = None,
      originalName  = fnName,
      mangledName   = fnName
    )

    Bnd(
      source     = SourceOrigin.Synth,
      nameNode   = Name.synth(fnName),
      value      = Expr(syntheticSource, List(lambda)),
      typeSpec   = Some(fnType),
      typeAsc    = Some(unitTR),
      docComment = None,
      meta       = Some(meta),
      id         = genId(moduleName, fnName)
    )

  /** Wrap a field access expression with a __clone_T call */
  private def wrapFieldWithClone(
    fieldExpr:   Expr,
    fieldType:   Type,
    moduleName:  String,
    resolvables: ResolvablesIndex
  ): Expr =
    val typeName    = TypeUtils.getTypeName(fieldType).getOrElse("String")
    val cloneFnName = TypeUtils.cloneFnFor(typeName, resolvables).getOrElse(s"__clone_$typeName")
    val cloneFnId   = resolveMemFnId(typeName, cloneFnName, moduleName, resolvables)
    val cloneFnType = Some(
      TypeFn(syntheticSource, cats.data.NonEmptyList.one(fieldType), fieldType)
    )
    val cloneFnRef =
      Ref(SourceOrigin.Synth, cloneFnName, resolvedId = cloneFnId, typeSpec = cloneFnType)
    val cloneApp = App(syntheticSource, cloneFnRef, fieldExpr, typeSpec = Some(fieldType))
    Expr(syntheticSource, List(cloneApp), typeSpec = Some(fieldType))

  /** Rewrite a __mk_StructName constructor to mark heap-typed params as consuming */
  private def rewriteConstructor(
    struct:      TypeStruct,
    resolvables: ResolvablesIndex,
    members:     List[Member]
  ): List[Member] =
    val constructorName = s"__mk_${struct.name}"
    members.map:
      case bnd: Bnd if bnd.name == constructorName =>
        val lambdaOpt = bnd.value.terms.collectFirst { case l: Lambda => l }
        lambdaOpt match
          case Some(lambda) =>
            val newParams = lambda.params.zip(struct.fields.toList).map { (param, field) =>
              if isOwnedField(field, resolvables) then param.copy(consuming = true)
              else param
            }
            val newLambda = lambda.copy(params = newParams)
            bnd.copy(value = Expr(bnd.value.source, List(newLambda)))
          case None => bnd
      case other => other

  /** Rewrite a native struct constructor to mark heap-typed params as consuming */
  private def rewriteNativeConstructor(
    td:          TypeDef,
    ns:          NativeStruct,
    resolvables: ResolvablesIndex,
    members:     List[Member]
  ): List[Member] =
    val constructorName = s"__mk_${td.name}"
    members.map:
      case bnd: Bnd if bnd.name == constructorName =>
        val lambdaOpt = bnd.value.terms.collectFirst { case l: Lambda => l }
        lambdaOpt match
          case Some(lambda) =>
            val newParams = lambda.params.zip(ns.fields).map { (param, field) =>
              if isNativeHeapField(field._2, resolvables) then param.copy(consuming = true)
              else param
            }
            val newLambda = lambda.copy(params = newParams)
            bnd.copy(value = Expr(bnd.value.source, List(newLambda)))
          case None => bnd
      case other => other

  /** Build a `__clone_StructName` function for a user struct.
    *
    * Generated pattern:
    * {{{fn __clone_User(s: User): User = __mk_User (__clone_String s.name) (__clone_String s.role)}}}
    *
    * Heap fields are explicitly cloned before passing to the constructor, which consumes its args.
    */
  private def mkCloneFunction(
    struct:      TypeStruct,
    moduleName:  String,
    resolvables: ResolvablesIndex
  ): Bnd =
    val structName = struct.name
    val fnName     = s"__clone_$structName"
    val paramName  = "s"

    // Type refs
    val structTypeRef =
      TypeRef(syntheticSource, structName, struct.id, Nil)

    // Parameter - not consuming since we're cloning (borrowing)
    val param = FnParam(
      SourceOrigin.Synth,
      Name.synth(paramName),
      typeAsc   = Some(structTypeRef),
      consuming = false
    )

    // Build the constructor type as a curried function: T1 -> T2 -> ... -> StructType
    val fieldTypes = struct.fields.map(_.typeSpec).toList
    val constructorType = fieldTypes.foldRight(structTypeRef: Type) { (fieldType, accType) =>
      TypeFn(syntheticSource, cats.data.NonEmptyList.one(fieldType), accType)
    }

    // Constructor reference: __mk_StructName
    val constructorName = s"__mk_$structName"
    val constructorRef = Ref(
      SourceOrigin.Synth,
      constructorName,
      resolvedId = Some(s"$moduleName::bnd::$constructorName"),
      typeSpec   = Some(constructorType)
    )

    // Build arguments: extract each field, wrapping heap fields with __clone_T
    val argExprs: List[Expr] = struct.fields.toList.map { field =>
      val paramRef    = Ref(SourceOrigin.Synth, paramName, typeSpec = Some(structTypeRef))
      val fieldRef    = Ref(SourceOrigin.Synth, field.name, qualifier = Some(paramRef))
      val fieldAccess = Expr(syntheticSource, List(fieldRef), typeSpec = Some(field.typeSpec))

      if isHeapField(field, resolvables) then
        wrapFieldWithClone(fieldAccess, field.typeSpec, moduleName, resolvables)
      else fieldAccess
    }

    // Build constructor call: __mk_StructName arg1 arg2 ...
    // Track the result type through each curried application
    val (constructorCall, _) =
      argExprs.foldLeft((constructorRef: Ref | App | Lambda, constructorType)) {
        case ((fn, currType), arg) =>
          val resultType = currType match
            case TypeFn(_, _, ret) => ret
            case other => other
          val app = App(syntheticSource, fn, arg, typeSpec = Some(resultType))
          (app, resultType)
      }

    val body = Expr(syntheticSource, List(constructorCall), typeSpec = Some(structTypeRef))

    // Build the function type: StructName -> StructName
    val fnType = TypeFn(syntheticSource, cats.data.NonEmptyList.one(structTypeRef), structTypeRef)

    // Build the lambda
    val lambda = Lambda(
      syntheticSource,
      List(param),
      body,
      Nil,
      typeSpec = Some(fnType),
      typeAsc  = Some(structTypeRef)
    )

    // Build the binding
    val meta = BindingMeta(
      origin        = BindingOrigin.Function,
      arity         = CallableArity.Unary,
      precedence    = Precedence.Function,
      associativity = None,
      originalName  = fnName,
      mangledName   = fnName
    )

    Bnd(
      source     = SourceOrigin.Synth,
      nameNode   = Name.synth(fnName),
      value      = Expr(syntheticSource, List(lambda)),
      typeSpec   = Some(fnType),
      typeAsc    = Some(structTypeRef),
      docComment = None,
      meta       = Some(meta),
      id         = genId(moduleName, fnName)
    )

  /** Main entry point - generate memory functions for structs with heap fields */
  def rewriteModule(state: CompilerState): CompilerState =
    val module     = state.module
    val moduleName = module.name

    // Find all user structs
    val structs = module.members.collect { case s: TypeStruct => s }

    // Find structs that own resources (heap fields or function-value fields)
    val structsNeedingMemFns = structs.filter(structHasOwnedFields(_, module.resolvables))

    // Find native structs with heap fields (constructor rewrite only, no free/clone generation)
    val nativeStructsWithHeapFields = module.members.collect { case td: TypeDef =>
      td.typeSpec.collect {
        case ns: NativeStruct
            if ns.fields.exists(f => isNativeHeapField(f._2, module.resolvables)) =>
          (td, ns)
      }
    }.flatten

    if structsNeedingMemFns.isEmpty && nativeStructsWithHeapFields.isEmpty then state
    else
      // Rewrite constructor params: mark heap-typed params as consuming
      val membersWithRewrittenCtors = structsNeedingMemFns.foldLeft(module.members) {
        (members, struct) =>
          rewriteConstructor(struct, module.resolvables, members)
      }

      // Also rewrite native struct constructor params
      val membersWithAllCtors = nativeStructsWithHeapFields.foldLeft(membersWithRewrittenCtors) {
        case (members, (td, ns)) =>
          rewriteNativeConstructor(td, ns, module.resolvables, members)
      }

      // Update resolvables with rewritten constructor Bnds
      val allCtorNames =
        structsNeedingMemFns.map(s => s"__mk_${s.name}") ++
          nativeStructsWithHeapFields.map { case (td, _) => s"__mk_${td.name}" }
      val rewrittenCtors = allCtorNames.flatMap { ctorName =>
        membersWithAllCtors.collectFirst { case b: Bnd if b.name == ctorName => b }
      }
      val resolvablesWithCtors = rewrittenCtors.foldLeft(module.resolvables) { (idx, bnd) =>
        idx.updated(bnd)
      }

      // Generate __free_T for every owning struct. Function-value fields are wired in later by
      // `wireStructClosureFrees` once `__free_closure` exists. Generate __clone_T only for structs
      // that hold no function value (directly or transitively): a captured env is not deep-copied,
      // so such structs are not clonable.
      val generatedFns = structsNeedingMemFns.flatMap { struct =>
        val freeFn = mkFreeFunction(struct, moduleName, resolvablesWithCtors, false)
        if TypeUtils.containsFunctionField(struct, resolvablesWithCtors) then List(freeFn)
        else List(freeFn, mkCloneFunction(struct, moduleName, resolvablesWithCtors))
      }

      val finalMembers = membersWithAllCtors ++ generatedFns
      val finalResolvables = generatedFns.foldLeft(resolvablesWithCtors) { (idx, fn) =>
        idx.updated(fn)
      }

      state.withModule(module.copy(members = finalMembers, resolvables = finalResolvables))

  /** Regenerate struct destructors so they free function-value fields through `__free_closure`.
    *
    * `__free_closure` is created by `ClosureMemoryFnGenerator` after type checking, so the closure
    * field frees cannot be emitted when the destructor is first generated (`__free_closure` is
    * neither resolvable nor typeable at that point). This runs from the closure generator, after
    * `__free_closure` exists, and replaces each function-bearing struct's `__free_StructName` with
    * one that also frees its function-value fields.
    */
  def wireStructClosureFrees(state: CompilerState): CompilerState =
    val module     = state.module
    val moduleName = module.name

    val functionBearingStructs = module.members.collect {
      case s: TypeStruct if TypeUtils.hasFunctionField(s) => s
    }

    if functionBearingStructs.isEmpty then state
    else
      val rewrittenFrees = functionBearingStructs.map { struct =>
        mkFreeFunction(struct, moduleName, module.resolvables, true)
      }
      val freeById = rewrittenFrees.map(bnd => bnd.name -> bnd).toMap

      val newMembers = module.members.map {
        case bnd: Bnd if freeById.contains(bnd.name) => freeById(bnd.name)
        case other => other
      }
      val newResolvables = rewrittenFrees.foldLeft(module.resolvables) { (idx, bnd) =>
        idx.updated(bnd)
      }

      state.withModule(module.copy(members = newMembers, resolvables = newResolvables))
