#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
JAR_PATH="$SCRIPT_DIR/mmlc.jar"

if [ -f "$JAR_PATH" ]; then
  exec java -jar "$JAR_PATH" "$@"
  exit $?
fi

echo "Error: Could not find mmlc.jar in $SCRIPT_DIR"
exit 1
